### ISSUE TITLE
Error while executing

### ISSUE THREAD

**Issue by Miraklefix** [dmustanger/7dtd-ServerTools#145]
> 2018-12-23T11:00:10 2249.288 ERR [MODS] Error while executing PlayerSpawnedInWorld on mod "Server Tools"
> 2018-12-23T11:00:10 2249.288 EXC Object reference not set to an instance of an object
> NullReferenceException: Object reference not set to an instance of an object
>   at ServerTools.SQLiteDatabase.TQuery (System.String _sql) [0x00000] in <filename unknown>:0 
>   at ServerTools.SQL.TQuery (System.String _sql) [0x00000] in <filename unknown>:0 
>   at ServerTools.API.PlayerSpawnedInWorld (.ClientInfo _cInfo, RespawnType _respawnReason, Vector3i _pos) [0x00000] in <filename unknown>:0 
>   at ModEvent`3[ClientInfo,RespawnType,Vector3i].Invoke (.ClientInfo _a1, RespawnType _a2, Vector3i _a3) [0x00000] in <filename unknown>:0 

Allways at startup

**Desktop (please complete the following information):**
 - OS Linux Ubuntu 16.04.5 LTS 64bit
 - ServerTools Version 12.6

**Additional context**
That happens too:

> 2018-12-23T10:23:55 73.948 INF ---------------------------------------------------------------
> 2018-12-23T10:23:55 73.948 INF [SERVERTOOLS] Verifying configuration file & Saving new entries
> 2018-12-23T10:23:55 73.948 INF ---------------------------------------------------------------
> 2018-12-23T10:23:55 73.952 WRN [SERVERTOOLS] Ignoring Set_Home entry because of missing 'Vehicle' attribute: <Tool Name="Set_Home" Enable="True" Set_Home2_Enabled="True" Set_Home2_Donor_Only="False" Delay_Between_Uses="60" Command_Cost="0" PvP_Check="False" Zombie_Check="False" />
> 2018-12-23T10:23:55 73.953 WRN [SERVERTOOLS] Ignoring Waypoints entry because of missing 'Vehicle' attribute: <Tool Name="Waypoints" Enable="True" Max_Waypoints="3" Donator_Max_Waypoints="6" Command_Cost="5" Delay_Between_Uses="0" PvP_Check="False" Zombie_Check="False" />
> 2018-12-23T10:23:55 73.966 ERR [MODS] Error while executing GameStartDone on mod "Server Tools"

 And an Error while loading the SQL Files:

> Fallback handler could not load library /home/sdtd/engine/7DaysToDieServer_Data/Mono/x86_64/SQLite.Interop.dll
> Fallback handler could not load library /home/sdtd/engine/7DaysToDieServer_Data/Mono/x86_64/libSQLite.Interop.dll.so
> Fallback handler could not load library /home/sdtd/engine/7DaysToDieServer_Data/Mono/x86_64/./SQLite.Interop.dll
> Fallback handler could not load library /home/sdtd/engine/7DaysToDieServer_Data/Mono/x86_64/./libSQLite.Interop.dll.so

[log.txt](https://github.com/dmustanger/7dtd-ServerTools/files/2705907/log.txt)

Thank you for updating this nice tools!

**Comment by ijurisic** [comment]
That is great news

**Comment by Miraklefix** [comment]
Very good news my friend!

LG
Armin Raab

Von meinem IPhone, welches nun ein Upgrade erfahren hat, gesendet.

**Comment by albiejames** [comment]
Here's a band-aid fix that I implemented on my gcloud x86_64 Debian server.

I compiled the interop assembly release from [source](https://system.data.sqlite.org/downloads/1.0.109.0/sqlite-netFx-full-source-1.0.109.0.zip) on my Debian server. If you rather compile from source, download and unzip the source code, `cd` to Setup, and run:
`./compile-interop-assembly-release.sh` (you will need the gcc compiler installed of course)
I then placed the .dll and .so libraries under ../Mono/x84_86 on my server
And it worked. 

This is just a band-aid fix that will probably work for most Debian based distros. I tested this on Debian 9 and Ubuntu 18.04 LTS server builds. I suspect it might segfault on other distros but you never know until you try.

**Comment by Chazarus** [comment]
Hello fellow zombie slayers,

I run a Linux based dedicated server and was also encountering a comparable issue where the latest version of server tools would not connect to a database - be it sqlite or mysql.

Host: Linux mint 18.3 (64bit)
ServerTools: 12.7

The main issues were:

1. The  ServerTools.LoadProcess.Load() method is called out of sequence, so that state 2 (set up the database) is executed before state 4 (load the settings from the config file).  Due to this, the database settings are not loaded so ServerTools always tries to use Sqlite even if MySql is set in the config file.

2. The system.data library being used is the one from full .net rather than mono - so on a linux host a lot of the dependencies cannot be resolved and it all ends badly.  Its the one thing I took to heart with cross platform unity development.....  remember that its mono when going cross platform :)

3. It was using Sqllite from a nuget package which was using interop versions of the libraries.  Great for windows and full .Net..... not so great on a penguin based architecture with mono without messing around recompiling libraries.

I have implemented a few changes on a local copy of the source to change the references and alter the order of ServerTool.LoadProcess.Load() and this resolves the bulk of the issues I have encountered (although I am getting the odd syntax error from a couple of the MySQL queries - but this might just be a version thing)

I was planning to run the code for a day or so under various combinations of Windows + SqLite / Windows + MySQL / Linux + SqLite / Linux + MySQL to see if anything else falls out and then submit a pull request if that is welcome.

**Comment by Chazarus** [comment]
Fairly confident that all the bugs are resolved, so I have now submitted a pull request.

I did encounter a MySQL specific bug because one of the columns in the Players table is called "return" which is a reserved word in MySQL which makes it sad :(

Rather than renaming I have just fully qualified the column in the Sql statements which fixes the issue for MySQL and maintains compatibility with Sqlite.

**Comment by ObsComp** [comment]
Awesome Chaz. I caught those same errors too :)  I have switched the load process around and found some strangling errors that can occur with some linux distro. The streamwriter to create an xml file can be busy and so fail to create the xml files entirely or only get one file sometimes and need to restart. It was inconsistent so I realize that is likely what causes it. I will make that into its own class operation to prevent bottleneck with it.

Also the sql needs a que when writing to the db to prevent the db in a busy state.

I have switched the mysql to a nuget based version for windows and will compile the linux one with a mono based one. I thought I did already but I will try again.

**Comment by ObsComp** [comment]
I also stripped sqlite out for the linux version as it will not be used of course

**Comment by Chazarus** [comment]
I would leave the sqlite in unless you have a compelling reason to remove
it - using the built in mono libraries and the dll straight from the sqlite
website it works with no further setup / tweaking required.  Save having to
set up a dedicated MySql server :)

**Comment by XelaNull** [comment]
> Here's a band-aid fix that I implemented on my gcloud x86_64 Debian server to get sqlite working
> 
> I compiled the interop assembly release from [source](https://system.data.sqlite.org/downloads/1.0.109.0/sqlite-netFx-full-source-1.0.109.0.zip) on my Debian server. If you rather compile from source, download and unzip the source code, `cd` to Setup, and run:
> `./compile-interop-assembly-release.sh` (you will need the gcc compiler installed of course)
> I then placed the .dll and .so libraries from ../bin/2013/Release/bin into ../7DaysToDieServer_Data/Mono/x86_64 on my server
> And it worked.
> 
> This is just a band-aid fix that will probably work for most Debian based distros.
> 
> I tested this on Debian 9 and Ubuntu 18.04 LTS 64 bit server builds. I suspect it might segfault on other distros but you never know until you try.
> [sqlite3-libs.zip](https://github.com/dmustanger/7dtd-ServerTools/files/2718613/sqlite3-libs.zip)

Thank you SO much for posting this! This was exactly the tip I needed to get this working. I made sure to carefully document the exact commands as I worked through this.

I've confirmed these steps work on CentOS7 as well. Here are the *exact* steps I'm using and have tested:
# Sqllite Manual Compile & Fix for ServerTools 12.7 under CentOS 7
`yum install gcc-c++ unzip wget -y && \
cd $INSTALL_DIR && mkdir sqllite && cd sqllite && \
wget https://system.data.sqlite.org/downloads/1.0.109.0/sqlite-netFx-full-source-1.0.109.0.zip && \
unzip sqlite-netFx-full-source-*.zip && \
cd Setup && chmod a+x compile-interop-assembly-release.sh && ./compile-interop-assembly-release.sh && \
cp ../bin/2013/Release/bin/* $INSTALL_DIR/7DaysToDieServer_Data/Mono/x86_64/`

$INSTALL_DIR is your 7DTD Game installation directory where your Mods folder resides. With the exception of the "yum" command above, which would vary depending on your Linux distro.. the above code snippet should run on any Linux system running 7DTD. gcc, unzip, and wget are also very easily obtained on all Linux distros and may already be installed anyway.

**Comment by ObsComp** [comment]
Linux users rejoice. ST 12.94 is for alpha 17.2 and contains fixes for linux users. Please follow the instructions you will find in the linux fixes zip file.

ST 12.72 is for alpha 17.1 and contains the linux fixes.
