### ISSUE TITLE
Licence of the mod

### ISSUE THREAD

**Issue by MatthiasMiebach-Aracom** [dmustanger/7dtd-ServerTools#148]
Hi ,

i really like your mod and want to use it on my own server... but it is missing some features i would like.
As i am also a developer instead of just opening a feature-request i would like to modify this tool by myself.
As i don't find any licence here i am not sure if and how i am allowed to do this...
Would it be okay if i just fork the mod and add/change some stuff?

Greetings :smiley:

**Comment by ObsComp** [comment]
Yup. We leave it open source for others to do as they please. If you would like to work with us, I can speak with Dmust and see what he says.

What are you trained in and what are you interested in working on? We are open to suggestions.

Lots of plans ahead but we have held off actually developing this in any real detail because the game has been in such a garbage state it is not worth it.

Many tools are slated for refinement, extra options, simplicity and bug fixes but we are still in alpha and sadly going into beta again with these experimental alphas. I personally have been more focused on Yellow Vest protests in my country versus games but I am going to be working on ST this week to try and get out a reasonable and stable release.

Do you use discord?
