### ISSUE TITLE
Issue - [Bank] and [Home] commands!

### ISSUE THREAD

**Issue by kl486134862** [dmustanger/7dtd-ServerTools#178]
**Describe the bug**
After restarting the server. 

1. The money saved in the bank and wallet will be gone.
2. Also the [/sethome], [/home] will be reset.

**How To Reproduce**

1. Deposit the money in the bank or wallet. And I restart the server. the money will be deleted.
2. [/sethome] . After restarting the server, the home location was gone.

**Expected behavior**

1. After restarting the server, the money should be inside the bank and wallet.
2. Also, the [/sethome] should not be reset.

**Desktop
 OS: [Windows 10]
 ServerTools Version [18.1.4]
Running with the RAT admin tool.
[output_log_dedi__2019-11-23__01-34-20.txt](https://github.com/dmustanger/7dtd-ServerTools/files/3880801/output_log_dedi__2019-11-23__01-34-20.txt)

**Comment by ObsComp** [comment]
2019-11-23T01:35:28 64.740 ERR [SERVERTOOLS] Failed loading GimmeItems.xml: Name cannot begin with the '5' character, hexadecimal value 0x35. Line 50, position 55.
2019-11-23T01:35:28 64.749 ERR [SERVERTOOLS] Failed loading Shop.xml: Data at the root level is invalid. Line 1, position 1.

Just a heads up. You have some errors in your shop.xml and gimme.xml

**Comment by ObsComp** [comment]
We need an output log corresponding to the events in game you are reporting about. This is an output log from a server that was booted up and closed right after.

We need to see what is happening when you operating those commands in game and what the log shows.

I suspect you may have another mod operating that is conflicting or running the commands instead of ST. RAT manager has a lot of features like a bank and wallet if I recall.

To be able to help identify the source of the issue, we will need another output log as mentioned prior.

I can not replicate this issue you describe in tests so I am quite sure one of those mods you are running is conflicting.

**Comment by kl486134862** [comment]
The problem Fixed. I just move up the server tools to first. add a 1 to make it load higher.
