### ISSUE TITLE
Bed despawns when you die

### ISSUE THREAD

**Issue by mengseth** [dmustanger/7dtd-ServerTools#183]
Hey. We had a problem on the server. Players died and bed despawned. first i removed all mods and tested with one and one mod.. Bed stayed.   When i tested with ServerTools, the bed despawned. i did nothing in the config files for ST
[output_log_dedi__2019-12-05__07-10-59.txt](https://github.com/dmustanger/7dtd-ServerTools/files/3926739/output_log_dedi__2019-12-05__07-10-59.txt)

**Comment by CBree** [comment]
I'm not sure it is this mod, the bedroll de-spawning is a known bug in 7 Days - I found that it only really happens in a new game, and once you place it down after death, it seems to work fine. I still get the issue on new servers, even ones with zero mods.
One thing to check, have you enabled Hardcore mode in the ServerToolsConfig.xml?

**Comment by dmustanger** [comment]
I believe this has been fixed in the latest version

**Comment by ObsComp** [comment]
This should be fixed in the latest versions. Pimps left a terrible bug in the bed system where people could spawn on the wrong bed point. It has been altered to prevent this but had a mistake so it was corrected. When you place a bed, it checks for anyone else sharing the same point and if so, removes it and alerts the players effected immediately. This should prevent any issues. Please report bed issues if you believe it is not functioning correctly with version 18.2.1+
