### ISSUE TITLE
GamePath should not be set to CWD

### ISSUE THREAD

**Issue by maci0** [dmustanger/7dtd-ServerTools#204]
https://github.com/dmustanger/7dtd-ServerTools/blob/2d2903fb68405ccbde773474f3f80df213b6420b/ServerTools/src/Api.cs#L13

Should rather be relative to savefolder and not based on CWD as the user can execute from anywhere.

My cwd was / so it tried to create //ServerTools which of course no permissions unless you're root.

**Comment by ObsComp** [comment]
The save folder is by default in a hidden location under %appdata% of windows. Essentially hidden from users so it was done this way to utilize a game path and location users could find but I will consider a better method. It was meant to go from the location of the executable but I will have to alter this since some use links and in the case of linux, the struct is different

**Comment by ObsComp** [comment]
ServerTools now uses the UserDataFolder for installation so you can specify the location that you would like to use or install it to your existing user data folder. I am closing this topic
