### ISSUE TITLE
sqlite fix doesn't need file to be located in Mono directory

### ISSUE THREAD

**Issue by maci0** [dmustanger/7dtd-ServerTools#205]
i just dropped the sqlite interop .so file into my .local/share/7DaysToDie directory and set my LD_LIBRARY_PATH to also look there when executing the server binary. 
worked just fine. no need to meddle with static data from the game folder

**Comment by maci0** [comment]
just putting it in the Mods/ServerTools directory works fine too. no need for LD_LIBRARY_PATH

**Comment by ObsComp** [comment]
Thanks. I have removed SQLite in the most recent edition to simplify the process for users and to allow the tool to work on Linux based operating systems.

I will keep that in mind if it comes up again. That used to cause issue for astar manager on the server load. It would allow the server to start up but zombies were stuck standing in one spot due to astar manager locking up.
