### ISSUE TITLE
Request for change (Website port configuration)

### ISSUE THREAD

**Issue by Letoric** [dmustanger/7dtd-ServerTools#220]
Can you please consider making the website port definable? Providers often don't open a lot of ports per server, and it would be useful to be able to define them so we can squeeze as much out as possible. Might also be useful if you could just leverage Alloc's web server, if present, which would be even better for hosted platforms.

**Comment by ObsComp** [comment]
It utilizes a port 4 higher than the control panel port. You can change the control panel port to get the port you are looking for but it is done this way to avoid overlap of other managers. ST runs a custom encryption cipher and algo for the website security. Due to this allocs back end web server is not appropriate. Allocs webmap uses 2 higher than the control panel port, CSMM is +3 and ST is +4

**Comment by ObsComp** [comment]
I could likely give you this option but I can also see people put things like 8080 and ask why its not working while not giving any output logs to boot lol

I will think about some ways to customize it tho. Maybe just block a few specific ones

**Comment by Letoric** [comment]
I would appreciate you trying, and I'm sure providers would as well. You'll never be able to completely account for user stupidity, it's called server-tools, they have to take some responsibility for being server administrators at some point :)

**Comment by ObsComp** [comment]
This has been added as an option in recent versions. Please try the latest release 19.4.4 for the web panel
