### ISSUE TITLE
Remote Buy

### ISSUE THREAD

**Issue by DemonRem** [dmustanger/7dtd-ServerTools#236]
can i add command that allow players to buy items ammo from any region they are? for example in day 7 when they are camping on some home?

**Comment by ObsComp** [comment]
Yep. You can do it through the Shop tool. After turning the shop tool on a Shop.xml file will be created in your ServerTools folder. Edit this file and add your own custom entries to the list. Use the items.xml for the item names.

You can set how many they receive and how much it costs.

It utilizes the Wallet tool as well because the game does not have the ability to withdraw items from a players inventory. Due to this it uses a digital wallet to buy things through the shop or to run specific commands you set command costs for.

You can exchange the default in game coins in to wallet coins through the bank tool.

They place casinoCoins in a chest and deposit them in to the bank and then withdraw from the bank to the wallet.
