### ISSUE TITLE
PROTECTION (PVE) does not work at 100%

### ISSUE THREAD

**Issue by LPMZ** [dmustanger/7dtd-ServerTools#257]
Hello, I have half of the map in pve works with firearms and fighting weapons, but all explosives like grenades, dynamites, Rocket Launcher. Aah robotic hammer and junk turret can Kill you. I am using servertools version 19.0.11, it is the most stable as it does not block players with the "ban". Will that be corrected in a future update?

**Comment by ObsComp** [comment]
Honestly I have not worked on that version in quite some time.

So pve protection does not work when it is an explosive based attack or turrets?

PvE was changed in later versions. The current version is 19.3.1 and does not require you to ban anyone. You can set the PvE infraction values so that if someone were to violate a pve space a certain amount of times, they will be jailed, killed, kicked or banned. Up to you what to set it as. You can always put them to 0 so that it doesnt apply.

<Tool Name="PvE_Violations" Jail="4" Kill="6" Kick="8" Ban="10" />

If I were to shoot you 4 times inside a pve space or while I was in one, I would be jailed. If I continued after that I would be killed for 6 violations and then kicked for the 8th or banned for the 10th. I could set any of those to 0 so that they dont apply.

**Comment by Zipcore** [comment]
The punishment can't work on such damage sources when you don't check against them. You only check for player entity vs player entity damage. Explosives, fire & turrets are not a player entity.

**Comment by ObsComp** [comment]
Very true. I discovered this issue a while back. Turrets for example like to toss the makers steam id through it and not the entity id of the source... which is a little tricky lol. I have to check location data and flesh out the tool a bit more. I will work on it for sure. Thanks for the report

**Comment by Zipcore** [comment]
You may need to patch ProcessDamageResponseLokal aswell (same header) to hook damage done by mines for example
https://github.com/dmustanger/7dtd-ServerTools/blob/master/ServerTools/src/Harmony/RunTimePatch.cs#L19

**Comment by ObsComp** [comment]
I have rechecked all of the damage processes with the implementation of the new modes implemented in 19.6.0 of ServerTools. It should all be fixed in the upcoming version 19.6.2

Tests look very good for both standard damage and explosive. It no longer inflicts pve penalties unless they are inside the market or lobby while protected. It will instead stop the damage and warn them they are doing nothing
