### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by Nackenschelle** [dmustanger/7dtd-ServerTools#27]
Server is not creating ServerToolsConfig.xml
is there any solution for me?

i did everything in the description

**Comment by credomane** [comment]
On the server console what does entering the command `version` give you?
Should get something like this:

    Game version: Alpha 16.4 (b8) Compatibility Version: Alpha 16.4
    Mod Server Tools: 5.8

There are two things I can think of.

1st) Are you putting ServerTools in the wrong place? *This* was the big gotcha I ran into when starting with 7dtd mods. There is a pre-made Mods folder in 7DaysToDieServer_Data folder for some reason. They don't actually go in that folder and everyone says, "Just put it in the Mods folder. It will work." They never say what Mods folder or where it is. :(

Anyways the ServerTools folder (with the ServerTools.dll inside) should be located in the Mods folder in the root 7DTD folder. The root being the one with 7DaysToDieServer.x86 and 7DaysToDieServer.x86_64 executables. So that is `<7dtd root>/Mods/ServerTools/ServerTools.dll`

2nd) Are you looking for ServerToolsConfig.xml in the wrong place?
The config file won't be created next to the ServerTools.dll I missed that reading the docs.
On Linux it will appear in the folder `~/.local/share/7DaysToDie/Saves/ServerTools/` of whatever user is running the 7dtd server.
On Windows I assume it will be `C:\users\<username>\AppData\Roaming\7DaysToDie\Saves\ServerTools`

**Comment by Nackenschelle** [comment]
ok thx fixed the issue

**Comment by ObsComp** [comment]
Excellent! Glad it is working out for you all
