### ISSUE TITLE
Protected Spaces

### ISSUE THREAD

**Issue by DaREWster** [dmustanger/7dtd-ServerTools#272]
Protected spaces not working properly. Any eta on when or if this will be fixed?

**Comment by DaREWster** [comment]
The issue I'm having is it protects a small box on the edge of the area its supposed to.

**Comment by Zipcore** [comment]
Mins = SouthWest corner
Maxs = NorthEast corner

**Comment by ObsComp** [comment]
I will try and get a better guide together on how it works. It definitely needs a major update to avoid bugs with the tool itself. I will update the How To Setup after it is updated so that it makes sense to how it ends up working. This is on the list for next update and high priority. Been bugged for far too long. Sorry it has take this long but the fix is coming

**Comment by ObsComp** [comment]
ETA... well I am working on the web panel stuff this week so that is back in order and more functional. Next week I will work on this list of bugs and so I could see a patch addressing this around 04/15/2021 latest

**Comment by ObsComp** [comment]
Should be fixed in 19.4.1. Let us know if you still have issues
