### ISSUE TITLE
Waypoints configuration claim!

### ISSUE THREAD

**Issue by LPMZ** [dmustanger/7dtd-ServerTools#273]
Hi, I wanted to know if in the next update they can extend the configuration of the "Waypoints" so that people can use "tp" having a "claim" because there is no configuration on that.

**Comment by ObsComp** [comment]
You would like them to be able to place waypoints inside claims and an option to enable/disable the claim protection?

**Comment by ObsComp** [comment]
It was made this way because home points are inside of claims and waypoints are outside of them. To avoid conflict in the code checks and differentiate the two, it was done in this manner. Are you after more home points in particular? I am updating ST to allow customized home location values so the admin can set how many players have with a separate one for donors/reserved players. It will work similar to the waypoint system
