### ISSUE TITLE
need a updated How_To_Setup.txt file

### ISSUE THREAD

**Issue by Davinel17** [dmustanger/7dtd-ServerTools#281]
some features and option are not explained. 
a updated explication file it will be great 

like the "protected" option into the zone feature , what it do ? i was thinking everything was not destructible but it is.

**Comment by ObsComp** [comment]
I agree. I need to overhaul the entire file big time. Thank you for the reminder. I will make sure it is a priority for the upcoming patch.

**Comment by OmitLeChuck** [comment]
The file HowToSetup.txt helped me in many ways to find the right settings for my server.
But I would find it much cooler if the information could be found here on github in the wiki. Gladly with a few more details as well.

If help is needed, I'm happy to transfer the file to the wiki.
But also for other help, like language support for german (native language) I'm happy to support.

Since I have only started with C#, I can only provide limited support there.

**Comment by ObsComp** [comment]
Just updated the How to Setup in 19.4.4
Please download the latest patch and let us know if you would like to see more details and specific types of instructions.
