### ISSUE TITLE
how to login in web tools?

### ISSUE THREAD

**Issue by batboyboy1990** [dmustanger/7dtd-ServerTools#291]
how to login in web tools?

**Comment by ObsComp** [comment]
You turn on the Web_Panel tool in config. Access a console either in game or through telnet and enter st-web add steamid
This will add that steamid as a login. It requires a 17 character length login, so it doesnt have to be their steamid but it must be 17 characters. It will return their temp password for login. They can change this password after logging in.

Access the panel by going to http://YourIP:YourPort/st.html

Replace YourIP with your servers ip. The port is your default control panel port + 4. Typically your control panel is 8080 so you would need to enter 8084 for the web panel. This port must be opened/forwarded to you so that it can be accessed. If you are on a host, they must open this for you.

**Comment by batboyboy1990** [comment]
[http://upload.7daysbroad.ga/images/2021/05/04/1319-1614171569-709839399.png](url) 
i think not work

**Comment by maomiblog** [comment]
hi try this   `st-web add steamid`

**Comment by batboyboy1990** [comment]
> hi try this `st-web add steamid`

http://7daysbroad.ddns.net:8084/st.html

i understan but this http://7daysbroad.ddns.net:8084/st.html blank screen :( !!!!

**Comment by ObsComp** [comment]
You must use the host IP address, not the hosts URL.

________________________________

**Comment by ObsComp** [comment]
Web panel has been updated in 19.4.4
It should be fully functional now.
You still need to use the IP address, not the URL of your host.
