### ISSUE TITLE
Zones after upgrade 19.4.2 (19.4.3)

### ISSUE THREAD

**Issue by GETRE4DY** [dmustanger/7dtd-ServerTools#295]
Updated version 19.4.0 to 19.4.2 (3) and the zones that worked fine before stopped working for me. 

`INF [SERVERTOOLS] Error in API.GameStartDone: Index was outside the bounds of the array.`

ST completely unavailable on the server.

```
<?xml version="1.0" encoding="UTF-8"?>
<Zones>
    <Zone>
        <Zone Corner1="-8000,0,8000" Corner2="8000,200,0" Circle="false" Name="North" EntryMessage="You are entering the Northern side" ExitMessage="You have exited the Northern Side" Response="" ReminderNotice="You are still in the North" PvE="false" NoZombie="false" />
    </Zone>
</Zones>
```

Here are the default coordinates, they don't work either.

**Comment by LPMZ** [comment]
I have the same problem, I had to go back to 19.4.0

**Comment by batboyboy1990** [comment]
> I have the same problem, I had to go back to 19.4.0

19.4.3 the trigger error, Phrases too! 19.4.0 ist best!

**Comment by ObsComp** [comment]
I just ran some tests using 19.4.4 and had no issues setting up a new zone. 

INF [SERVERTOOLS] Error in API.GameStartDone: Index was outside the bounds of the array.
was being caused by another tool from my understanding. The Web_Panel in particular was doing this.

Please try the latest release and let us know if you still have issues.
