### ISSUE TITLE
Add a server restart command.

### ISSUE THREAD

**Issue by BoQsc** [dmustanger/7dtd-ServerTools#316]
I'd like to have a command to restart a server.

And in the configurations you could select a relative or absolute path to the script file that starts the server.

**Comment by ObsComp** [comment]
You can shutdown a server using servertools but you can not restart the server. ST only runs while the server is active so you must use a third party to restart it.  We recommend setting your server as a service to auto restart. If you are on a host, most have an auto restart feature.

There is a command to begin a shutdown. Access a console for your server and type st-ss 'minutes'. Example: st-ss 2
This will start a countdown of two minutes with warnings you are about to shutdown. You can run the default shutdown from the base game which is immediate. To do that, run shutdown in a console.

I could add that feature.

**Comment by rAmfu** [comment]
Why? Use Linuxgsm and servertool..

> I'd like to have a command to restart a server.
> 
> And in the configurations you could select a relative or absolute path to the script file that starts the server.

Why? Use Linuxgsm and servertool..

**Comment by ObsComp** [comment]
A restart function has finally been added, JOY! 

20.5.0 has a restart tool. Thank you for the suggestion

**Comment by Bananaman** [comment]
That's cool. It wasn't mentioned in README.md, but I saw it in the changelog:

```
-Added Auto_Restart tool. As the name says, it will restart
your server when shutdown. This may not work or interfere
with hosts that provide their own restart function
```

I am guessing that it basically makes the server process spawn a 2nd detached server process (child) at the moment when it's about to terminate itself. So that the child then lives on.

If so, it would definitely interfere with tools like LinuxGSM, which is based on process ID monitoring. Just saying this so that people keep it in mind. On Linux, it's better to use LinuxGSM and setting up a cron/systemd timer that runs the LinuxGSM `monitor` command every minute, which in turn starts the server automatically if it's off.

That way, ServerTools handles the scheduling of the shutdown, and LinuxGSM's monitor will handle the startup after that.
