### ISSUE TITLE
Vehicles customized for Vehicle_Teleport.

### ISSUE THREAD

**Issue by LPMZ** [dmustanger/7dtd-ServerTools#320]
I have modified vehicles only from the server side, I wanted to know if in an update it will be possible to add custom vehicles in "Vehicle_Teleport", by the way I tried the vanilla ones and I see that you can put the meters Distance = "50" increases it to 4000 meters and does not bring it to you. This command is implemented by the bug of disappearance of vehicles ?.

**Comment by ObsComp** [comment]
Custom vehicles. Hmm, I think so. A custom vehicle list should work. If you match up the entity names, yeah, I dont see why not

If you try to teleport a vehicle, bag/backpack or any type of entity from a chunk of the world that is not currently loaded via a player near by, it wont work. It can even say it teleported them but it wont. I would have to implement a chunk check and turn on an observer to teleport things outside of the players current chunk range. That will work for some things but not others so I would have to test it a bit and let you know. Recommend vehicles be no more than 200 blocks away for now. It forces people to not use it as a teleport system but rather for recovering the vehicles if they fall down a pit for example or get stuck in a wall.

This is also why protected spaces do not always implement properly since the chunk is not loaded. I have to work on how to load chunks from raw data so that I can modify them despite it not being loaded

**Comment by ObsComp** [comment]
I have redone the entire code for vehicles. It will allow you to use custom vehicles. You set the maximum number a player can save for normal players and for reserved. They save it by sitting on it, typing /recall . They can see a list of their vehicles with /recall while not using one or teleport/recall it if within distance by using /recall {Id}   The id is shown in the list of vehicles. If all works out you will also be able to increase the range dramatically from the original limitations

**Comment by ObsComp** [comment]
New changes will be in 19.6.2
