### ISSUE TITLE
 (Crash server) SvTools 19.5.3

### ISSUE THREAD

**Issue by LPMZ** [dmustanger/7dtd-ServerTools#323]
Hello, A few days ago I had it activated and the players complained that "the zombie drop backpacks" disappeared, also the vehicles were teleported at the end of the map. Suspected it was the falling block remover. When deactivating it, the server crashed. now turn off the server then deactivate falling_block these errors do not happen anymore.

**Comment by LPMZ** [comment]
The "crashes" continue, remove the servertools and stop "crashing the server", I tried the SvTools version 19.5.2 and the same thing continues. Several days of testing I realized that the "protecction_spaces". and gimme, Starting items commands. crash the server. I have deactivated it and for now I have not received any crash !. It happens in svTools version 19.5.2 and 19.5.3. I leave the logs of my server:  [](https://www.mediafire.com/file/ws31prhziwq9f5p/output_log_2021-06-06_160706.rar)
I keep testing.

**Comment by ObsComp** [comment]
Please try the latest 19.6.1. It will auto update your xml files to the latest version. If some of your custom entries are lost, manually put them in to the new xml by using the xml backups. Something sounds off with your server or files. You might want to install a fresh copy of servertools rather than just update.

I will test the block remover again to be sure it is not crashing anything. Were you testing it on something special or a particular poi?

**Comment by ObsComp** [comment]
Are you running an old ServerTools.bin file? It is possible something has happened to it.

If you notice ServerTools reporting anything strange to your output log, let us know.

**Comment by LPMZ** [comment]
No, delete all the servers tools up to the .bin file and set everything to 0 manually. Since I disable Protected_Spaces.xml, Starting_Items.xml, gimme.xml. It does not freeze, 4 days have passed and no "Crash".
I made a prison with protected_spaces so players can get past the horde. I remember that the server in the horde sometimes froze, not always, not even a shutdown worked, it had to terminate processes. This happened using 19.5.3. Then delete that protected region and disable block protection and it stopped freezing. Then enable Starting_Items.xml it worked fine, but then the "Crash Server" came back again and I realized that when many new players entered together it happened.
Anyway, what interests me is that the protection (PVE) works correctly, so I am now with 19.5.2. and with those settings disabled.
I will try the latest version and let you know.

**Comment by ObsComp** [comment]
I have noticed the game does not like trying to spawn multiple thing too quickly, especially where it then makes the player pick it up automatically. I suspect I need to not only slow down the spawn of the items but also que the new players so that they do not all have it run at the same time like that. It can be improved to do that for sure. I will mark it down as an improvement

**Comment by ObsComp** [comment]
I added a small delay to the spawn a while back and it stopped the crashes from StartingItems at least... however I removed it. Silly me. I will definitely improve that for you. As for protected spaces. That needs a full over haul if possible or else I may remove it as it does not function how it should and can cause more problems than it solves
