### ISSUE TITLE
Web API error

### ISSUE THREAD

**Issue by FastCDr** [dmustanger/7dtd-ServerTools#327]
Hello!
I have installed the server on centos 8.
Everything works.
But there is one problem that I cannot solve in any way.
The web panel and web api do not work.
Error:
webpanel logs: The host ip could not be determined. Web API is disabled
console log: INF [SERVERTOOLS] Error in WebAPI.SetBaseAddress: Error: TrustFailure (One or more errors occurred.)
INF [SERVERTOOLS] Host IP could not be verified. Web API has been disabled
 INF [SERVERTOOLS] The host ip could not be determined. Web API is disabled

Can you tell me what could be wrong?

**Comment by ObsComp** [comment]
ST does a third party IP check due to the process and pimps code not providing the IP until later in the load process. By the error reported, it sounds like you have security to block this IP check and so it responds with a trust failure. If I change the way to loads, I can likely just wait for the server to be fully done loading and then start the web api/panel where I should be able to verify the IP at that point from the pimps code rather than a third party call out.

If I had to guess though, it is a security feature of your OS preventing ST from running that

**Comment by ObsComp** [comment]
This will be fixed for you in 19.6.3 coming out later today
