### ISSUE TITLE
Vehicle recall.

### ISSUE THREAD

**Issue by LPMZ** [dmustanger/7dtd-ServerTools#328]
I am trying commands / recall does not work for me, Also how do I remove a vehicle from the id list? 
![1313](https://user-images.githubusercontent.com/53027365/131261370-c80ae66e-7504-4653-8f39-941abb7b4850.png)

**Comment by mohamedalb** [comment]
i have the same issue

**Comment by ObsComp** [comment]
Yeah I am not happy with the way the tool has turned out. There are limitations due to chunks being loaded or in some cases, not loaded. If you are way outside of the range and try to teleport it, it doesnt have a chance because the game doesnt even report that it exists in the world. It is there but stored in either cached files or region files that have to be reloaded.

I will work on this for 19.6.5. I would recommend keeping it off for now

**Comment by ObsComp** [comment]
The vehicle recall has been redone and improved tremendously. The only true limit you should find now is the distance that can be set via the config. If it exists in the world, it can be recalled. Use commands /vehicle save, /vehicle, /vehicle #, /vehicle del
