### ISSUE TITLE
Custom Commands and Login phrases not working

### ISSUE THREAD

**Issue by Corleone91** [dmustanger/7dtd-ServerTools#334]
Custom Commands and Login phrases not working

**Comment by SodiumDetector** [comment]
I believe I might be having the same issue. I cant seem to get clients added or at least login phrases working.

**Comment by ObsComp** [comment]
Sorry I was quite busy coding the next release. 19.6.4 is out. Give it a shot and let us know if you are still having issues. Phrases needs one more major update to get it in line with the upgrade process. Currently, new phrases added will not show up until the file is fully regenerated or you add it yourself. To regenerate the file, delete it. It will create a new one for you while the server is running. 

Custom commands should not be having any issues except for the permission system which is fixed in 19.6.4. Can you explain the problem you are having with that one a bit more? Please provide the command you are attempting to run by cut and pasting it from your .xml file to here.

Check that your output log is not reporting any major issues on server load up or when tools are activated

**Comment by ObsComp** [comment]
Version 19.6.5 is out. Some important fixes were added. I noticed a few xml files were wiped out during the upgrade process before. Double check they are not blank. That would explain why you are having issues. This problem is fixed now.
