### ISSUE TITLE
Pve system does not work. Ammo infinite bans. Xray no message! v19.6.6 

### ISSUE THREAD

**Issue by LPMZ** [dmustanger/7dtd-ServerTools#345]
The pve system does not work. I have it like this my server is configured in pvp 
`<property name="PlayerKillingMode" value="2" />`

and so "server tools" zones.xml:
  `<Zone Name = "Example" Corner1 = "2464,0,1509" Corner2 = "2192,500,988" Circle = "false" EntryMessage = "You have entered example" ExitMessage = "You have exited example" EntryCommand = "whisper This is a pve space "ExitCommand =" "ReminderNotice =" You are still in example "PvPvE =" 0 "NoZombie =" True "/>`

The "ammo infinite" system banned for no reason and I have it disabled. When I use the admin gun! 
Xray works correctly but does not say any message, only servertools appear in chat. Small detail! :)

PD: With the pve system, it cannot be left similar to version "19.5.2"? This version works well the "pve violation" I have it in kick mode and I used it for months and it did not bring me any problem because when kicking the player all the conflict that the pve system has is debugged!

**Comment by ObsComp** [comment]
PvPvE has a flaw in it I am trying to sort out. You know of it, their model goes stiff and stops taking damage. I removed the pve penalties when they could not damage them any more. It was not needed anymore but after finding out about the model bug, I had to back off forcing the player mode switch which is when I discovered it can still have the bug when it prevents damage to players.

Infinite had a bug indeed. I fixed it and just released a patch right now. 19.6.7. It was sending bad meta data when using a launcher type weapon such as bows and the admin gun yes. I changed that for 19.6.7 as well.

XRay does show a message but the phrases.xml does not update the same way as the others. You are likely just missing the phrase that was added. I still have to reform how that one works, try not to break it and keep all of your custom entries while adding missing ones on the update process. I plan to recode how the phrase system works and when I do, I can open it up to a lot of possibilities like multiple responses, random responses, player stats and various parameter options instead of having them only offered on specific ones.

Please try 19.6.7 and let me know if you are still having problems.

As for the PvPvE system, let me keep working on this model bug. If I can find how to solve that, I can go back to preventing all damage and not worry anymore

**Comment by ObsComp** [comment]
I am wondering if when it checked the mode match and they were incorrect, I would tell it to not allow the damage. I should probably allow the clients to run the operation despite the mismatch except in the case of explosions of course. The clients should simulate the same as the server in that case and not damage each other. Maybe the client was simulating it despite no damage going through. Just a guess. I will play with it

**Comment by LPMZ** [comment]
Great, thank you so much for the xray system !!. The message is unnecessary the same !. it works 100% better to leave it like that.
With the issue of pve I insist it is better to return to the "pve violation" system if it is not a lot of work. do not go crazy it is better to kick the player so that the error of the rigid model does not happen. Also, the alpha 20 is about to come out and I don't think all of this is compatible with that version.
In the afternoon I test 19.6.7 and report if I find something wrong.

**Comment by ObsComp** [comment]
How are you finding the accuracy of the XRay detection so far?

**Comment by LPMZ** [comment]
mmm now it works when it wants haha. ADMIN of
![A19 6_2021-11-17_13-45-42](https://user-images.githubusercontent.com/53027365/142244610-97f51a01-76d8-4eb9-993e-c940737b0c53.jpg)
f!
