### ISSUE TITLE
wallet a20 not working

### ISSUE THREAD

**Issue by batboyboy1990** [dmustanger/7dtd-ServerTools#354]
a20 not work money in wallet
protect backback notworking
protect tools not working

**Comment by Rival819** [comment]
I also confirm that /wallet his not working.

**Comment by ObsComp** [comment]
The wallet system changed. There is no longer a /wallet. You receive casinoCoins or in game currency which you can change if you wish.
The casinoCoins in your bag are your wallet now

**Comment by ObsComp** [comment]
I will double check the other two tools

**Comment by batboyboy1990** [comment]
> The wallet system changed. There is no longer a /wallet. You receive casinoCoins or in game currency which you can change if you wish. The casinoCoins in your bag are your wallet now

So can orders use COID money?

**Comment by ObsComp** [comment]
With the ServerTools installation files was a folder named Config. Inside of that is a file named items.xml. This is an xpath document that alters the default items.xml for the game to include the word currency on the casinoCoin. I need the item to have this currency tag in order to exchange the item directly from their backpack. You can change this file to target any item that you wish. This can be a custom item you have created.

Commands that include a cost will take the currency you have selected from the players backpack

________________________________

**Comment by Rival819** [comment]
THIS THREAD HAS BEEND FIXED: WALLET NOW GIVES DUKES DIRECTLY INTO INVENTORY, /WALLET COMMAND REMOVED IN NEW VERSION !
