### ISSUE TITLE
Add Anti Drone Duping, Need to Prevent Player Teleport.

### ISSUE THREAD

**Issue by Rival819** [dmustanger/7dtd-ServerTools#366]
Players can teleport with drones deployed therefore duping all item in its inventory and also multiplying the drone itself creating drones to remove everywhere. Need to add prevention to /home, /way and also /lobby systems for drone teleport prevention.

**Comment by ObsComp** [comment]
This should be fixed in the base game now. We try not to fix base game bugs like that. It often requires altering the games code in ways that can get complicated later on after they fix it and we will have to drop the fix once they patch it anyways. The time is better spent reporting the bug to the devs and then working on various other tools ST provides beyond the base game. Sorry that is not a great response but it is the truth. If the devs were not planning to fix that, we would step in and fix it for them.

Has it been fixed? I have not heard of any issues with drone and duping anymore.

**Comment by michaelarlt** [comment]
It was supposed to be fixed and it doesn't happen only if you teleport. Also if you die and get back to the place where you died it can happen. So @ObsComp is totally right. This is a Game Bug and needs to be fixed by TFP. I dont see any sense in fixing a major bug for someone else if there is still ongoing development. It sounds rude, but if you're worried about the duping just disable porting! But you cant prevent player to die which also causes the duping sometimes.
StevenTube, not known for porting and stuff does have 3 drones already in Video https://www.youtube.com/watch?v=vvpwyZ2I_ag Timestamp 0:20. Two Videos later there were 5
He dies now and then and this most probably causes them to dupe
