### ISSUE TITLE
Does not work with APlha 20.5

### ISSUE THREAD

**Issue by James-Knullify** [dmustanger/7dtd-ServerTools#389]
I am not receiving any errors that I notice none of the enabled commands are working with Alpha 20.5. Some enabled are bad words, admin list, lottery, private message.

**Comment by ObsComp** [comment]
I have just released version 20.5.0 of ST. Give that a try. If you are still having the same issue, please provide a copy of your latest output log and we can review it, then give advice on fixing it

**Comment by CosMic92** [comment]
I'm trying to install the lastest version, clean install. the folder <ServerTools> will not be created, the folder that includes servertoolsconfig.xml. could this be related?

**Comment by Digrade** [comment]
> I'm trying to install the lastest version, clean install. the folder will not be created, the folder that includes servertoolsconfig.xml. could this be related?

Exactly the same problem

**Comment by Digrade** [comment]
Is it possible to release a small video on the correct installation of the plugin.Or if it already exists, where to find it.
And I apologize in advance for writing in this topic

**Comment by Arcadelord** [comment]
Greetings,

I've freshly installed your Tool Kit on my server. Latest version available.
Unless I've been doing something wrong with the process, it should be working just fine.
Excepting that it doesn't due to unknown reasons.
I'll upload screenshots of the in-game chat as well as the server's installation, to see if the problem comes from me or not.
I've installed the Tool Kit while the server was offline, activated the tools that I wanted to see working with "True" within the ServerToolsConfig.xml, then restarted the server.

![7 Days to Die Screenshot 2022 07 03 - 13 46 51 88](https://user-images.githubusercontent.com/108612392/177038349-6c9b0d07-ac08-4835-9846-2f05e23e23a3.png)
![Screenshot 2022-07-03 at 13-47-48 Pingperfect - File Manager](https://user-images.githubusercontent.com/108612392/177038366-5aaa7c6f-c13c-48a8-bea6-f3b8f3a2f195.png)
![Screenshot 2022-07-03 at 13-48-19 Pingperfect - File Manager](https://user-images.githubusercontent.com/108612392/177038370-1b0cd134-8602-4839-a738-ceb5a6668d5f.png)
![Screenshot 2022-07-03 at 13-48-29 Pingperfect - File Manager(1)](https://user-images.githubusercontent.com/108612392/177038375-0588eaff-c13a-47a1-aee1-b28f8d649077.png)

Hopefully this help with my issue and your investigation.

**Comment by ObsComp** [comment]
:)  pimps have really taken us for a spin on this one. The mods folder we are all used to is changing. To get ahead of this upcoming change, ServerTools is now using the User Data Folder. This is typically specified in the ServerConfig.xml for your server. If this has not been specified, it defaults to the system AppData folder.

If you are on a host, I suggest you ask them about their suggested file location to meet this requirement.

Pimps(game devs) currently allow two locations for the Mods folder to reside and load from which is VERY confusing for users. They will eventually drop support for the location most people are used to. That location is normally inside your main directory the server files are installed to.

From now on, always install your Mods to the user data folder/app data location instead of the old location. Take heed, some older mods may be hard coded to work with the old location and cause issues after shifting to the new one.

Here is where my own Mods folder is located now by default. I do not specify a user data folder in my config so it goes here.

C:\Users\...\AppData\Roaming\7DaysToDie\Mods

Let me know if this helps or if you are still having problems after moving the files.

**Comment by Wolfshad3** [comment]
still no workaround?
cos on dedicated servers we wont get any access to the root folders :)

**Comment by ObsComp** [comment]
There is no need for a work around. All mods will be going to the ...UserDataFolder/mods in the future. Eventually the devs will drop support for the old location. They have kept the old location so that all of your mods did not break immediately.

Make sure to place the installation files in ...UserDataFolder/Mods/ServerTools

ServerTools will generate a new folder on start up as long as the installation files are located in the correct spot.
The new folder will be located at ...UserDataFolder/ServerTools

You can specify the user data folder in your ServerConfig.xml from the base game

Latest release is 20.6.0 as of today

**Comment by ObsComp** [comment]
I have opened it up to allow both locations. I still recommend that you use the new user data folder since the old location will not work eventually but for the time being, you can use both. When they do eventually switch it over and close the old location, switching to the new location will be the same process I have described prior. No need for an update to ST, just to switch the file location.

For the time being, use the old location if that is simpler and works for you
