### ISSUE TITLE
Resetting ServerToolsConfig.xml on every server restart

### ISSUE THREAD

**Issue by reapa1234** [dmustanger/7dtd-ServerTools#396]
Not 100% sure if it is a server thing or something to do with the mod itself but upon restarting my server it seems to be resetting my ServerToolsConfig.xml back to default.

**Comment by ObsComp** [comment]
Curious, do you have a few custom commands?

**Comment by ObsComp** [comment]
Version 20.6.0 has been released. It has a fix for something in custom commands that may have been causing that. Give it a shot and let me know

**Comment by ObsComp** [comment]
This may have been due to Custom_Commands tool. Something has been added to prevent that during start up in version 20.6.2. Please update to the latest and let us know if the problem persists

**Comment by FeliciaMoon** [comment]
I know this thread is closed but I'm having the same issue ever since I updated to A20.6.2 could someone help me out not even the host where I'm renting my server from seems to know the reason and I don't use custom commands either have tried with both true and false and either way my servertoolsconfig.xml resets, spending more times redoing it while in-game to do it until next time......
