### ISSUE TITLE
I can't change the coin , it will not recognize new coin

### ISSUE THREAD

**Issue by lcdblunt** [dmustanger/7dtd-ServerTools#424]
![ss1](https://user-images.githubusercontent.com/95121464/210278860-3267b5e9-29be-4350-b296-4ab1c4abf0a8.png)
![ss2](https://user-images.githubusercontent.com/95121464/210278861-fbff7ee5-7295-4b1f-a9c5-365ae9dcd3d6.png)
![ss3](https://user-images.githubusercontent.com/95121464/210278862-5b126a09-7a56-4fb1-8c6d-f1f9cae3a995.png)
I need some help

**Comment by lcdblunt** [comment]
![ss4](https://user-images.githubusercontent.com/95121464/210278992-d4efba14-8ac6-40fc-9f22-4c58c8685c52.png)

**Comment by ObsComp** [comment]
Everything looks correct there. Is it still an issue for you in more recent versions? You can add currency to your custom item directly as an alternative way to enable its use. Sometimes you need to due to the load order of the mods. For the Tags section, add currency the same way it shows it from the xpath. "dukes,currency"

**Comment by ObsComp** [comment]
I found a bug in the load process that will be fixed on next patch. Depending which version you are on, it may work or not. I fixed it at one time but recently broke it in a new way. I will be more cautious of it and make notes

**Comment by ObsComp** [comment]
This is fixed in version 21.1.0 that will be released soon
