### ISSUE TITLE
Some errors i found

### ISSUE THREAD

**Issue by krazybeat** [dmustanger/7dtd-ServerTools#439]
No_Vehicle_Drone not working.
Rainbow in 'Custom Colors' not working.
Block_Logger aways show broke 'AIR'.
when creating a clan does not display the {ClanName}.

**Comment by ObsComp** [comment]
No_Vehicle_Drone is not a tool. Are you looking at a different mod?

Rainbow is an example and you must remove the comments. Comments look like this   <!--   -- >  
There is a ColorList.xml and ChatColor.xml. You put people on the ChatColor list and the ColorList is optional. It is there so that you can call on the colors by name instead of rewriting the html color tags for each person. It also allows a list of colors people can rotate through if enabled

**Comment by ObsComp** [comment]
Block logger has been updated in the latest releases of ST. I am closing this entry for now. Please submit a new one if you continue to have issues in relation or a new subject
