### ISSUE TITLE
Getting kicked after joining my server

### ISSUE THREAD

**Issue by SkandalBeu** [dmustanger/7dtd-ServerTools#451]
Hey all,

I've been playing with my friends on a rented  Nitrado server with a couple of mods.

I have no issues connecting to the server but after joining it takes like 2 seconds and we're both getting kicked from the server.
The first time we couldn't fix the problem so we just restored a backup and lost a lot of progress.
After restoring the backup arround the same time while driving into another chunk we get stuck and kicked from the server.
Now everytime we join the server we're getting kicked immediately...

Does anybody has or had the same problem an got it fixed?

We've invested a lot of time and just want to play the game.

Thanks.

 

Log: 
https://pastebin.com/v0ATriYJ

 

Mods we use:
7D2D-Vehicle-Respawner-A21-main
Accurate ADS and No Crosshair A21
Clear_Bulletproof_Glass-main
CraftFromContainers
DayZSoundsV1.3
donovan-pickmeup
END-Z-main
ImprovedHordes
Jakmeister999's Enhanced HUD (Alpha 21)
KHA21-96BBM
KHA21-LockableInvSlots
No Loot Timers 1.1
Zombie Health Bar

**Comment by ObsComp** [comment]
This is a github for ServerTools dedicated server manager. Not really for general server administration. However I dont mind lending a hand. Going by your output log, there is nothing standing out except the mods for the most part are failing to load. They are either missing Mod Info files, have older versions or simply failed to load going by that output log. I would suggest removing the mods, double check you can join the game without them. Then shut down and add mods one or two at a time until you find which is preventing you from joining. You will also want to fix those so that they complete their load. No real point in them being there if most of them are failing to load anyways. Depending how you installed specific mods, they may be interfering with your base game files but fail to load, which would in turn mean you cant join. Just my guess
