### ISSUE TITLE
How do I use the Wall tool?

### ISSUE THREAD

**Issue by zachary-kaelan** [dmustanger/7dtd-ServerTools#466]
I'm in an area I claimed, and I built the frame of a wall. I activated wall mode, tried placing blocks in the two corners, didn't do anything. Tried it again with wood blocks, again didn't do anything.

![20230911213532_1](https://github.com/dmustanger/7dtd-ServerTools/assets/30245333/dc4cbe13-bd36-4344-a072-f65bfc09741f)

**Comment by ObsComp** [comment]
I think it was having some problems. I have recoded it for the upcoming release 21.1.4
Some final testing is being done before release today or tomorrow

All future development of ST will be posted to a new host site. You can find ST here
https://bitbucket.org/obsessive-coder/sevendaystodie-servertools/src/core/

you are likely using it properly but the bug was stopping it from working after the devs changed a few things about block names a few patches ago. It likely was not working all this time but I have it fixed in the upcoming version.

You place a writable crate or secure chest down. Put some wood or cement or brick blocks inside the crate/chest. Take a few by hand and place them near by while inside a claim. Oh but you enable the wall tool by typing /wall first and then lets say you placed a block at 0,0,0 and then another at 10,0,0, it will detect they match and grab the blocks from the crate/box, then place them in between the two blocks you just placed. 10 block distance limit and the block height has to match. It wont fill up vertically. When you place those blocks, their names were changing based on shapes so I found a way you should be able to place any shape and if it matches another close by, it will check for the main block in the chest such as wood blocks.

Version 21.1.4 with the fix will be posted today or tomorrow on Bit bucket

Please follow development there
