### ISSUE TITLE
System Karma

### ISSUE THREAD

**Issue by VitalGrigoryev** [dmustanger/7dtd-ServerTools#97]
Karma tracks various player parameters, game time and more)) and increases or decreases the permission level
permission level indicated in the chat prefix

more commands:
/inckarma EntityId
/deckarma EntityId
/setkarma  EntityId

Karma module must support commands stack

**Comment by ObsComp** [comment]
This sounds like a neat idea but not with the current way the game functions, sorry. However with that said, A17 is changing the chat filter system which would open up a feature like this. I would love to make it more or less open based that you program in whatever you want to happen from the karma levels but that is not viable without a script base to ServerTools and ST simply is not coded for that yet.

I would essentially need to know what the karma would be for. If you have no karma you cant chat yet until you gain 100 karma as an example. You cant use commands until 200 karma. If I set those options and allow you to choose how much is needed, that is easier to code but that is why I would need to know what the karma is for. Some people will want it to enter the PVP ring. Some want it for quests and events. It is unfortunately opening a front I can only guess at and it can get ugly with requests to refine the tool more which is what is happening with all the tools in ST over time. Sensibly I would want to make console commands for each operation and then open up each response function to a custom console command of your choice. This would mean you have to program the core function in a platform base piece by piece. An example would be that when a player joins your server, if their karma is under 50, it runs the console command mute player on them but then you also get admins wanting custom responses they can setup lol. 

Until the game hits A17, I have not been refining the tools to do things this intricate because the game is in an alpha state in its base code. They have upgraded to unity 2017 with A17 so I can finally start refining the tools, make more intricate operations, link the core of ST operations into each other, automate some processes I was not able to or I know need a lot of time refining and bug testing. A17 will also let us dedicate a thread operation to monitor more of the actions in game because Unity 2017 improved this vastly, to the point it should not hurt game performance like before.

A single tool in ST can sometimes be 800 lines of code or more :)

Intricate tools will reach 2000 lines by the time everything has been programmed with variable option allowances.

**Comment by VitalGrigoryev** [comment]
this function can modify the serveradmin.xml file by setting the permissionlevel level to a specific value for the SteamID of each player.
